#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

int main() {
    int N;
    printf("Enter the size of the array: ");
    scanf("%d", &N);
    int arr[N];
    #pragma omp parallel
    {
        #pragma omp single
        {
            printf("Array generated by Thread ID: %d\n", omp_get_thread_num());
            for(int i = 0; i < N; i++) {
                arr[i] = rand() % 10;
            }
        }

        #pragma omp for
        for(int i = 0; i < N; i++) {
            printf("Thread ID %d processed index %d: %d^2 = %d\n", 
                    omp_get_thread_num(), i, arr[i], arr[i] * arr[i]);
        }
    }

    return 0;
}
